MSDK-6849 -  Update the MSDK to 10.0.0
MimiHearingTechnologies/IntegrationExampleMSDK-iOS pull request #15
Opened 2024-02-15 16:56 UTC by nkosta

- Updates the MSDK to 10.0.0

2024-02-19 07:52 UTC, SalarZ requested changes
Just a few comments

2024-02-19 07:52 UTC, SalarZ commented on IntegrationExample/AppDelegate.swift
> +import SwiftUI
We don't need to import SwiftUI here.

2024-02-19 07:52 UTC, SalarZ commented on IntegrationExample/AppDelegate.swift
>  //        return try processing.activate(presetDataSource: .default(.init(fitting: fitting)))
We need to change it to use the configuration with `SinglePreset`.

2024-02-19 07:52 UTC, SalarZ commented on IntegrationExample/Processing/PartnerAudioProcessingController.swift
> +import SwiftUI
We don't need to import SwiftUI here.

2024-02-19 07:52 UTC, SalarZ commented on IntegrationExample/Processing/PartnerAudioProcessingController.swift
> +            try await session.isEnabled.apply(isEnabledValue)
I have a question: where and when do we need to use the `synchronizeApplicators` function?

2024-02-19 07:52 UTC, SalarZ commented on IntegrationExample/Processing/View/ProcessingViewModel.swift
> -                session.intensity.deliveryMode = .discrete(seconds: 0.2)
As we don't have the `deliveryMode` anymore, I think it's good to set the `uiControlDebounceBehavior` in the configuration.

2024-02-19 08:15 UTC, hozefa26 commented
@SalarZ since kosta is out this week, can you please make the changes you suggested and then i'll take a look at it?

2024-02-20 05:17 UTC, hozefa26 approved these changes
just pushed some minor changes but otherwise great work @SalarZ & @nkosta! 🚀

2024-02-20 07:40 UTC, SalarZ approved these changes
🚀 Thanks @hozefa26 for cleaning up.

2024-02-20 07:44 UTC, merged